### ISSUE TITLE
Less ressource expensive FloatingButton

### ISSUE THREAD

**Issue by RomanJos** [akshathjain/sliding_up_panel#109]
Hi I'm trying to show a floatingbutton that is attached to the sliding panel exactly like your exemple but without rebuilding the entire panel and background.

I have kind of achieved that by setting the panel transparent and adding the button in the panel and then adding the normal stuff after but the transparent respond to click events so I drag the panel by touching this empty area.
I then tried to make the panel a Stack with the overflow visible and moving the button using a negative top inside Positioned but the overflow automatically become hidden when I move it / its closed.
My best attempt so far did is adding directly the floating button inside your library in the Stack of "the actual sliding part" and obviously setting the overflow visible, it display perfectly but it doesn't register the click because its outside the Stack (I didn't thought about it).

I'm now running out of Idea because calling setState to just move the floatingbutton is really not necessary and its really laggy on the emulator.

Thank you !

**Comment by akshathjain** [comment]
You can create an `AnimationController` that has its value set to the `position` returned by the `onPanelSlide` callback. Then, try using an `AnimatedBuilder` that subscribes to the animation controller instead of calling `setState`. I'll admit that the example isn't ideal with regards to performance, nor is it intended to be (since its a very simple implementation for demonstration purposes). I'll update this and make it clearer in the documentation.

**Comment by RomanJos** [comment]
That will be cool but writing an animationbuilder, using the callback etc for a floating button seems overkill for me
if you attach the widget like I did in a positioned widget you could control where you want it to be on x and y but also in the stack for exemple on a "center the map on position" button we can put it behind the panel widget and move his height to show or hide it if the map is centered or not.
This way there is no callback and animation to worry about, its already in the panel.

That said if I want to make this widget a little woobly (just adding a delay on move) I couldn't because its in the stack, and the widget add to the panel size so if the widget is too much far from the actual panel it will block the scroll, so widget in the stack is not perfect

**Comment by akshathjain** [comment]
The AnimatedBuilder is a more general approach that allows many more UI elements to be rebuilt as a result of the panel position. For example, users may want to have multiple elements fade out as the panel moves upwards or have other elements move with the panel. Since this behavior can vary from one implementation to another, adding a specific feature that only allows a FAB to move up and down isn’t general enough for the more common use case.

**Comment by IbrahimYildirim** [comment]
It's possible to set the `renderPanelSheet = false`. Then you can crate your own panel as a `Stack` and add a top margin for the sheet where you fill that space with a **FloatingActionButton**
