### ISSUE TITLE
3 levels of height 

### ISSUE THREAD

**Issue by aytunch** [akshathjain/sliding_up_panel#12]
In addition to maxHeight and minHeight, there should be a defaultHeight. When the panel opens up, it should open in defaultHeight. And if maxHeight is bigger than defaultHeight and the user pulls the panel towards top, it should snap to maxHeight. This can be taken even further to make the panel full screen if pulled all the way. What do you think of this feature? It gives the end user much more flexibility and ease of use imho.

**Comment by akshathjain** [comment]
@aytunch This is a really good idea! I think if I understand this correctly, you mean to say that there should be another position that the panel can snap to in between the minHeight and the maxHeight? 

Also, what if this was expanded further so there could be a list of positions in between minHeight and maxHeight that the panel snaps to?

**Comment by aytunch** [comment]
@akshathjain Yes thats exactly what I mean. What you suggested is even better. The user can supply an array of snap positions for instance

**Comment by aytunch** [comment]
We would need another callback in this case. Something like onPanelSnap(int snapIndex)

**Comment by softmarshmallow** [comment]
Is this feature on development?

**Comment by eric-taix-teads** [comment]
I'm currently implementing this feature for my own application. For now I have just copied / pasted `SlidingPanelState` and modified the code in my own project. I'll create a PR when finished.

In the meantime I just want to let you know that:
  [ ] to avoid breaking changes, I've kept `minHeight` and `maxHeight` fields as it  
  [ ] I've added a new field `snapPositions` which aims to contain snap position (in pixels)  
  [ ] I've introduce a new state which is `SNAP` and which contains an snap index value to be able to open the sliding panel on a snap position

Not directly related to this feature, but I had to add a new field `hideBorderRadiusWhenOpened` to hide the border radius when the sliding panel is opened. Because as now I have multiple snap positions, the OPEN position takes the full height of the viewport and having a border radius in this position is not really expected ;-)

Also the behavior of dragging has changed a little: 
1- when dragging smoothly, the sliding panel spans to the nearest snap position (the same behavior as today when you reach half of the distance between the current span and the next one.
2- if you drag faster, there's no need to reach the half of the distance, the sliding panel will go to the next snap position automatically. 
3- if you drag very fast (even on a short distance) and if there's other span positions after the next one then the sliding panel won't stop to the next span position and will go to the following span position (it aims to be able to open or close the sliding panel in one drag even with 3 positions)


Below an animation to see it in action
![sp](https://user-images.githubusercontent.com/42940156/66708321-114d7900-ed4f-11e9-9a74-f6dc3d3976a4.gif)

**Comment by DangKhoi1811** [comment]
@eric-taix-teads are you still there ? Did you create a PR about this enhancement ?

**Comment by zigang93** [comment]
@eric-taix-teads yea.. i need this feature

**Comment by eric-taix-teads** [comment]
Nop, sorry but I did not have time to create a PR for now (multiple other side projects during my spare time).

**Comment by akshathjain** [comment]
This is going to be added in the next version of this package.

**Comment by akshathjain** [comment]
Implemented and will be pushed in v1.0.1.
