### ISSUE TITLE
Backdrop overlay only covers the body of the Scaffold

### ISSUE THREAD

**Issue by aytunch** [akshathjain/sliding_up_panel#15]
BottomNavigationBar and AppBar are not greyed out and can be interacted with.

**Comment by akshathjain** [comment]
The `SlidingUpPanel` only displays a backdrop and disables interactivity over the Widget assigned to the `body` when `backdropEnabled` is `true` and the `panel` is open. If you want the `backdrop` to display over the `AppBar` and the `BottomNavigationBar`, then those components must be nested inside the `body` of the `SlidingUpPanel`. For example, in the documentation:

```dart
@override
Widget build(BuildContext context){
  return Material(
    child: SlidingUpPanel(
      backdropEnabled: true,
      panel: Center(
        child: Text("This is the sliding Widget"),
      ),
      body: Scaffold(
        appBar: AppBar(
          title: Text("SlidingUpPanelExample"),
        ),
        body:  Center(
          child: Text("This is the Widget behind the sliding panel"),
        ),
      ),
    ),
  );
}
```

This greys out and disables the `AppBar` since the `Scaffold` (and therefore `AppBar`) are nested in the body of the `SlidingUpPanel`.

**Comment by aytunch** [comment]
@akshathjain  Thanks for the info:)
