### ISSUE TITLE
It would be cool to define a default state of the panel and having the navigator of context getting back to that state when popping it.

### ISSUE THREAD

**Issue by MasiaVittorio** [akshathjain/sliding_up_panel#21]
Like when you hit the android back button and the navigator automatically closes a ModalBottomSheeet. It would be cool to close (or open?) the panel automatically when the user press the system back button.

**Comment by akshathjain** [comment]
I’m probably not going to add this to the panel in the future only because I think it’s easier to use a WillPopScope widget and the panel controller to achieve the desired functionality (which is how I’ve done it in my projects in the past). 

This avoids adding unnecessary complexity to the package and handling of the countless edge cases associated with this.
