### ISSUE TITLE
The backdrop dismiss on tap should be called onTapDown instead of onTap, to be more consistent with other bottom sheet designs.

### ISSUE THREAD

**Issue by MasiaVittorio** [akshathjain/sliding_up_panel#24]
Or also leaving the choice to use a full tap or just a tapDown could be dope.

**Comment by akshathjain** [comment]
@MasiaVittorio I agree that more features are nice; however, there's a definite trade-off between simplicity / ease-of-use and customization. In order to keep the library simple for first time developers or those who are unfamiliar with Flutter, I don't think implementing these particular features are necessary, especially as the end result of onTap(), onTapDown(), and onTapUp() are, for all practical intents and purposes, the same with regards to closing the panel.

If devs do really want to implement these features, it's very simple given the new callbacks implemented in v0.3.0.
