### ISSUE TITLE
Set panel dynamically with controller

### ISSUE THREAD

**Issue by CtrlAltDft** [akshathjain/sliding_up_panel#45]
Hi, is it possible to have the controller being able to set the panel content? As i want to avoid using setState()

**Comment by akshathjain** [comment]
This is currently not possible and probably won't be implemented due to a high number of edge cases (e.g. users setting the panel body using a panel controller before attaching the controller to the sliding up panel). 

Also, calling setState() will have negligible performance impacts to your app (if that's why you're trying to avoid using it) 

I may reconsider this functionality in the future (I could see this as something useful)

**Comment by enricobenedos** [comment]
Hi @akshathjain, first of all thank you for this awesome package. 
At the moment I need exactly to set panel dynamically. I already understand that at the moment you won't add this feature. But have you got any suggestion about how to implement this feature manually?
In my case I have a ListView with a lot of cards. When the user tap on a card I will show the SlidingUpPanel and in this moment I need to set the correct content of the panel. Maybe I found a workaround but I think it is very bad.
